title: The Daily Ramblings Of Toby
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3091807754244655
  brandStrength: 0.7353644
  lightness: 0.4510433136019856
  brandColors:
    - '#fbfff4'
    - '#270f25'
    - '#b0c5c8'
    - '#583a44'
    - '#b59d85'
  rhythmicContrast: 0.52381512359716
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Toby Russell
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8082437
layout_spectrum: 1
