name: Toby Russell
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50278
title: The Daily Ramblings Of Toby
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfff4'
    - '#270f25'
    - '#b0c5c8'
    - '#583a44'
    - '#b59d85'
  brandStrength: 0.5681783193722367
  lightness: 0.4510433136019856
  saturation: 0.30918077542446554
  rhythmicContrast: 0.52381512359716
purpose: []
